[book]
authors = ["Emre Ergun"]
language = "en"
multilingual = false
src = "src"
title = "JavaScript TypeScript Explained"

[output.html]
git-repository-url="https://github.com/emre-ergun/mdbook-jsts"

[output.html.playground]
runnable = false